-- Create roles table
-- UUID will be generated by application layer
CREATE TABLE roles (
    id UUID PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    is_system BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default system roles with explicit UUIDs
INSERT INTO roles (id, name, description, is_system) VALUES
    ('00000000-0000-0000-0000-000000000001'::UUID, 'admin', '系统管理员，拥有所有权限', TRUE),
    ('00000000-0000-0000-0000-000000000002'::UUID, 'editor', '编辑者，可以创建和编辑文档', TRUE),
    ('00000000-0000-0000-0000-000000000003'::UUID, 'viewer', '查看者，只能查看文档', TRUE);

-- Create index
CREATE INDEX idx_roles_name ON roles(name);
