-- Create permissions table
-- UUID will be generated by application layer
CREATE TABLE permissions (
    id UUID PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    resource VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    description TEXT
);

-- Insert default permissions with explicit UUIDs
INSERT INTO permissions (id, name, resource, action, description) VALUES
    ('10000000-0000-0000-0000-000000000001'::UUID, 'document:create', 'document', 'create', '创建文档'),
    ('10000000-0000-0000-0000-000000000002'::UUID, 'document:read', 'document', 'read', '查看文档'),
    ('10000000-0000-0000-0000-000000000003'::UUID, 'document:update', 'document', 'update', '编辑文档'),
    ('10000000-0000-0000-0000-000000000004'::UUID, 'document:delete', 'document', 'delete', '删除文档'),
    ('10000000-0000-0000-0000-000000000005'::UUID, 'user:manage', 'user', 'manage', '管理用户'),
    ('10000000-0000-0000-0000-000000000006'::UUID, 'system:config', 'system', 'config', '系统配置');

-- Create index
CREATE INDEX idx_permissions_resource ON permissions(resource);
